# Generated by Django 3.1.13 on 2021-07-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_follows'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
